#print("Hello", "Saurabh", 2+2, True, 3*5)
print("Hi, My name is Abhishu", "Nandwani")
print("Hi", "Abhishu", "Nandwani",sep="-", end="")
print("Hi", "Abhishu", "Nandwani", end="\t")
print("Hi", "Abhishu", "Nandwani")
